정영훈/README.md
정영훈/Week01/README.md
정영훈/Week01/수영장(BottomUp).cpp
정영훈/Week01/수영장(TopDown).cpp
정영훈/Week02/README.md
정영훈/Week03/README.md
정영훈/Week04/README.md
정영훈/Week05/README.md
정영훈/Week05/구간 나누기2.cpp
정영훈/Week05/머리 맞대기.cpp
정영훈/Week05/코딩 테스트 공부(DFS - 50).cpp
정영훈/Week05/코딩 테스트 공부(DP - 100).cpp
정영훈/Week05/코딩 테스트 공부(DP - topdown)(연구중).cpp
정영훈/Week05/프로세서 연결하기.cpp

ADD / week5 / 정영훈

---

이충혁/week7/스타트택시_baekjoon.cpp
이충혁/week7/자물쇠와열쇠_programmers.cpp
이충혁/week7/전화번호목록_baekjoon.cpp
이충혁/week7/줄기세포배양_SWEA.cpp

스타트 택시 : 맞추긴 했지만 코드가 깔끔하지 않아서 리팩토링 해서 다시 올리겠습니다.
줄기 세포 배양 : 완료
자물쇠와 열쇠 : 완료
전화번호 목록 : 완료

ADD / week7 / 이충혁

---

이충혁/week8/휴대폰자판_backjoon.cpp
이충혁/week9/구슬탈출2_baekjoon.cpp
이충혁/week9/등산코스정하기_programmers.cpp
이충혁/week9/큐빙_baekjoon.cpp

구슬탈출2 : 완료
등산코스 정하기 : 완료
큐빙 : 드디어 완료.... ㅠ

ADD / week9 / 이충혁

---

이충혁/week10/LCA2_baekjoon.cpp
이충혁/week10/표현가능한이진트리_programmers.cpp
이충혁/week10/히히못가(그래프안쓰기)_baekjoon.cpp
이충혁/week10/히히못가_baekjoon.cpp

LCA2 : 완료, LCA도 탐색 부분 만 뺴고 같은 코드로 되어 있습니다.
표현 가능한 이진트리 : 완료
히히 못가 : 완료 + 추가 풀이

ADD / week10 / 이충혁

---

탁성건/week10/11438-LCA 2.cpp
탁성건/week10/24515-히히 못가.cpp
탁성건/week10/표현 가능한 이진트리.cpp

ADD / week10 / 탁성건

---

이충혁/week11/광고삽입_programmers.cpp
이충혁/week11/치즈(확장판)_baekjoon.cpp
이충혁/week11/치즈_baekjoon.cpp
이충혁/week11/크루스칼의공_baekjoon.cpp

치즈 : 완료
크루스칼의 공 : LCA로 완료, 병령 이분탐색 미완료
광고삽입 : 완료 
광고 삽입 누적합 쓰시는 분들 longlong 조심하세요.... ㅠ

ADD / week11 / 이충혁

---

탁성건/week12/22949-회전 미로 탐색.cpp
탁성건/week12/3197-백조의 호수.cpp
탁성건/week12/매칭 점수.cpp

ADD / week12 / 탁성건

---

이충혁/week12/매칭점수_programmers.cpp
이충혁/week12/백조의호수_baekjoon.cpp
이충혁/week12/회전미로탐색_baekjoon.cpp

백조의 호수 : 완료
회전 미로 탐색 : 완료
매칭 점수 :  완료
-  점수 계산 할 때 double형으로 다 바꿔주기, map key값 겹칠 때 처리, double에서 입실론 더해주기 셋 다 아니었고 max 자료형 정수형이라 틀렸네요 ....

ADD / week12 / 이충혁

---

탁성건/week13/10999-구간 합 구하기 2.cpp
탁성건/week13/9328-열쇠.cpp
탁성건/week13/파괴되지 않은 건물.cpp

- 열쇠 / 구간 합 구하기 2 / 파괴되지 않은 건물

ADD / week13 / 탁성건

---

이충혁/week13/구간합구하기2_baekjoon.cpp
이충혁/week13/열쇠_baekjoon.cpp
이충혁/week13/파괴되지않은건물_programers.cpp

열쇠 : 완료
파괴되지않은건물 : 완료
구간 합 구하기 : 완료

ADD / week13 / 이충혁

---

이재홍/week13/10999_range_sum_2__2.cpp
이재홍/week13/10999_range_sum_2__3.cpp
이재홍/week13/9328_key.cpp
이재홍/week13/unbroken_building.cpp
이재홍/week13/unbroken_building__2.cpp

열쇠: 완료
구간 합 구하기 2: 완료, 정리한 코드도 업로드 완료
파괴되지 않은 건물: 완료

ADD / week13 / 이재홍

---

이충혁/week14/양과늑대_programmers.cpp
이충혁/week14/트리의순회_baekjoon.cpp
이충혁/week14/히스토그램(세그먼트트리)_baekjoon.cpp

트리의 순회 : 완료 
히스토그램 : 완료
양과 늑대 : 완료
연속합과 쿼리 : 미완료

ADD / week14 / 이충혁

---

탁성건/week14/1725-히스토그램.cpp
탁성건/week14/2263-트리의 순회.cpp

ADD / week14 / 탁성건

---

정영훈/README.md
정영훈/Week14/README.md
정영훈/Week14/양과 늑대.cpp
정영훈/Week15/README.md
정영훈/Week15/사라지는 발판(46.7).cpp
정영훈/Week15/사라지는발판.cpp
정영훈/Week15/연속합과 쿼리.cpp
정영훈/Week15/트리의 지름(1167).cpp
정영훈/Week15/트리의 지름(1967).cpp
정영훈/Week15/행성 터널,cpp

ADD / Week15 / 정영훈

---

이충혁/week15/사라지는발판_programmers.cpp
이충혁/week15/트리의지름_baekjoon.cpp
이충혁/week15/행성터널_baekjoon.cpp

트리의 지름 : 완료
사라지는 발판 : 완료
행성 터널 : 완료
연속합과 쿼리 : 미완료

ADD / week15 / 이충혁

---

탁성건/week14/양과 늑대.cpp
탁성건/week15/1167-트리의 지름.cpp
탁성건/week15/16993-연속합과 쿼리.cpp
탁성건/week15/2887-행성 터널.cpp

ADD / week15 / 탁성건

---

이충혁/week16/RGB거리2_baekjoon.cpp
이충혁/week16/도로네트워크_baekjoon.cpp
이충혁/week16/카드짝맞추기_programers.cpp

RGB거리2 : 완료
카드짝맞추기 : 완료
도로네트워크 : 완료
금광 : 미완료

ADD / week16 / 이충혁

---

탁성건/week15/사라지는 발판.cpp
탁성건/week16/17404-RGB거리 2.cpp
탁성건/week16/3176-도로 네트워크.cpp
탁성건/week16/카드 짝 맞추기.cpp

- 사라지는 발판
- 도로 네트워크 / RGB 거리 2 / 카드 짝 맞추기

ADD / week16 / 탁성건

---

이충혁/week17/다단계칫솔판매_programmers.cpp
이충혁/week17/책나눠주기_baekjoon.cpp

책 나눠주기 : 완료
다단계 칫솔 판매 : 완료
금광 : 미완료

ADD / week17 / 이충혁

---

탁성건/week17/9576-책 나눠주기.cpp
탁성건/week17/다단계 칫솔 판매.cpp

ADD / week17 / 탁성건

---

이충혁/week18/단절점_baekjoon.cpp
이충혁/week18/벨만포드_웜홀_baekjoon.cpp
이충혁/week18/벨만포드_타임머신_baekjoon.cpp
이충혁/week18/위상정렬_문제집_baekjoon.cpp
이충혁/week18/위상정렬_줄세우기_baekjoon.cpp
이충혁/week18/플로이드_역사_baekjoon.cpp
이충혁/week18/플로이드_플로이드_baekjoon.cpp

위상정렬 : 완료
MST : 완료
BCC : 단절점 완료 단절선 미완료

ADD / week18 / 이충혁

---

탁성건/week18/11266-단절점.cpp
탁성건/week18/11400-단절선.cpp
탁성건/week18/11404-플로이드.cpp
탁성건/week18/11657-타임머신.cpp
탁성건/week18/1613-역사.cpp
탁성건/week18/1766-문제집.cpp
탁성건/week18/1865-웜홀.cpp
탁성건/week18/2252-줄 세우기.cpp

- 최단 거리 찾기
- Bellman-Ford
- 타임머신
- 웜홀
- Floyd-Warshall
- 플로이드
- 역사
- 위상 정렬
- 줄 세우기
- 문제집
- BCC(Biconnected Component)
- 단절선
- 단절점

ADD / week18 / 탁성건

---

탁성건/week19/2150-Strongly Connected Component.cpp
탁성건/week19/3665-최종 순위.cpp
탁성건/week19/합승 택시 요금.cpp

- 최종 순위 / Strongly Connected Component / 합승 택시 요금

ADD / week19 / 탁성건

---

정영훈/README.md
정영훈/Week19/README.md
정영훈/Week19/Strongly Connected Component(Kosaraju).cpp
정영훈/Week19/Strongly Connected Component(Tarjan).cpp
정영훈/Week19/최종 순위.cpp
정영훈/Week19/합승 택시 요금.cpp

19주차 문제.
합승 택시 요금, Strongly Connected Component, 최종 순위

ADD / Week19 / 정영훈

---

이충혁/week20/기하_CCW_baekjoon.cpp
이충혁/week20/기하_다각형의면적_baekjoon.cpp
이충혁/week20/블록이동하기_programmers.cpp

ADD / week20 / 이충혁

---

박준섭/Week20/11758 CCW.cpp
박준섭/Week20/1219 오민식의 고민.cpp
박준섭/Week20/2166 다각형의 면적.cpp
박준섭/Week20/블록 이동하기.cpp

프로그래머스
- 블록 이동하기
백준
- CCW
- 다각형의 면적
- 오민식의 고민

ADD / week20 / 박준섭

---

탁성건/week20/11758-CCW.cpp
탁성건/week20/1219-오민식의 고민.cpp
탁성건/week20/13141-Ignition.cpp
탁성건/week20/2166-다각형의 면적.cpp
탁성건/week20/2325-개코전쟁.cpp

- Ignition / 개코전쟁 / 오민식의 고민
- CCW / 다각형의 면적

ADD / week20 / 탁성건

---

박준섭/Week21/24025 돌의 정령 줄세우기.cpp
박준섭/Week21/외벽 점검.cpp

ADD / WEEK21 / 박준섭

---

이충혁/week21/돌의정령줄세우기_baekjoon.cpp
이충혁/week21/외벽점검_programmers.cpp

돌의 정령 줄세우기 : 완료
외벽 점검 : 미완료 ( 44점 )

ADD / week21 / 이충혁

---

탁성건/week21/24025-돌의 정령 줄세우기.cpp
탁성건/week21/6086-최대 유량.cpp

ADD / week21 / 탁성건

---

탁성건/week22/17780-새로운 게임.cpp
탁성건/week22/2188-축사 배정.cpp
탁성건/week22/기둥과 보 설치.cpp

ADD / week22 / 탁성건

---

탁성건/week23/1339-단어 수학.cpp
탁성건/week23/1931-회의실 배정.cpp
탁성건/week23/길 찾기 게임.cpp

ADD / week23 / 탁성건

---

이충혁/week23/길찾기게임_programmers.cpp
이충혁/week23/단어수학_baekjoon.cpp
이충혁/week23/회의실배정_baekjoon.cpp

단어 수학 : 완료
회의실 배정 : 완료
길찾기 게임 : 완료

ADD / week23 / 이충혁

---

이충혁/week24/1로만들기_baekjoon.cpp
이충혁/week24/추석트래픽_programmers.cpp
이충혁/week24/파도반수열_baekjoon.cpp

1로만들기 : 완료
파도반수열 : 완료
추석트래픽 : 미완료 ( 77 점... )

ADD / week24 / 이충혁

---

탁성건/week24/1463-1로 만들기.cpp
탁성건/week24/9461-파도반 수열.cpp
탁성건/week24/추석 트래픽.cpp

ADD / week24 / 탁성건

---

탁성건/week25/2805-나무 자르기.cpp
탁성건/week25/3079-입국심사.cpp
탁성건/week25/5427-불.cpp

ADD / week25 / 탁성건

---

이충혁/week25/나무자르기_baekjoon.cpp
이충혁/week25/불_baekjoon.cpp
이충혁/week25/셔틀버스_programmers.cpp
이충혁/week25/입국심사_baekjoon.cpp

나무자르기 : 완료
입국 심사 : 완료
불 : 완료
셔틀버스 : 완료

ADD / week25 / 이충혁

---

탁성건/week26/14391-종이 조각.cpp
탁성건/week26/17069-파이프 옮기기 2.cpp
탁성건/week26/9095-1, 2, 3 더하기.cpp
탁성건/week26/경주로 건설.cpp

- 파이프 옮기기 2 / 종이 조각 / 1, 2, 3 더하기 / 경주로 건설

ADD / week26 / 탁성건

---

탁성건/week27/1405-미친 로봇.cpp
탁성건/week27/16926-배열 돌리기 1.cpp
탁성건/week27/16927-배열 돌리기 2.cpp
탁성건/week27/보석 쇼핑.cpp

배열 돌리기 1 / 배열 돌리기 2 / 미친 로봇 / 보석 쇼핑

ADD / week27 / 탁성건

---

이충혁/week28/동전0_baekjoon.cpp
이충혁/week28/수묶기_baekjoon.cpp
이충혁/week28/퍼즐_baekjoon.cpp

ADD / week28 / 이충혁

---

탁성건/week28/11047-동전 0.cpp
탁성건/week28/1525-퍼즐.cpp
탁성건/week28/1744-수 묶기.cpp

ADD / week28 / 탁성건

---

이충혁/week29/공유기설치_baekjoon.cpp
이충혁/week29/놀이기구탑승_codetree.cpp
이충혁/week29/랜선자르기_baekjoon.cpp
이충혁/week29/징검다리건너기_programmers.cpp
이충혁/week30/생명과학부랩인턴_codetree.cpp

ADD / week29 / 이충혁
